config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'pages#home'
  get 'about', to: 'pages#about'
  # resources :articles, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def show
  end

  def index
    @articles = Article.all
  end

  def new

  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = "Article was created successfully"
      redirect_to @article
    else
      render 'new'
    end
    # render plain: @article.inspect
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article ws updated successfully"
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy

    redirect_to articles_url, notice: "Article was successfully destroyed."
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end

  def about

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<% if !@article.nil? && @article.errors.any? %>
  <h2>The fallowing errors occurred</h2>
  <ul>
    <% @article.errors.full_messages.each do |err_msg| %>
      <li>
        <%= err_msg %>
      </li>
    <% end %>
  </ul>
<% end %>



<%= form_with(model: @article, local: true) do |f| %>
  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Editarticle</h1>

<%= render 'form' %>

<%= link_to 'Articles',  articles_path %> |

app/views/articles/index.html.erb
<h1>Articles listing page</h1>
<!--<ul>-->
<%# @articles.each do |article| %>
<!--  <li><%#= article.title %></li>-->
<%# end %>
<!--</ul>-->

<table>
  <thead>
    <tr>
      <td>Id</td>
      <td>Title</td>
      <td>Description</td>
      <td colspan="3">Actions</td>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.id %></td>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>Create a new article</h1>

<%= render 'form' %>


<%= link_to 'Articles',  articles_path %>

app/views/articles/show.html.erb
<h1>Showing article details</h1>
<p><string>Title: </string> <%= @article.title %></p>
<p><string>Description: </string> <%= @article.description %> </p>

<br>
<%= link_to 'Articles',  articles_path %> |
<%= link_to 'Edit', edit_article_path %> |
<%= link_to 'Destroy', @article, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <%= msg %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/messages' %>

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<p>About page</p>

<%= link_to 'Articles',  articles_path %> |
<%= link_to'Home', root_path %>

app/views/pages/home.html.erb
<p>Home page</p>

<%= link_to 'Articles',  articles_path %> |
<%= link_to'About', about_path %>